# Generated by Django 2.1.1 on 2018-09-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('ряд', 'Рядовой'), ('мл.снт', 'Младший сержант'), ('снт', 'Сержант'), ('ст.снт', 'Старший сержант'), ('лнт', 'Лейтенант'), ('ст.лнт', 'Старший лейтенант'), ('кн', 'Капитан'), ('мр', 'Майор'), ('ппк', 'Подполковник'), ('пк', 'Полковник')], default='ряд', max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('receipt_date', models.DateField()),
                ('promotion_date', models.DateField()),
                ('rebuke', models.BooleanField()),
            ],
        ),
    ]
